language: csharp
solution: ./src/System.Drawing.Analysis.sln
install:
  - nuget restore ./src/System.Drawing.Analysis.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:PostBuildEventUseInBuild=false /p:PreBuildEvent="" /p:PostBuildEvent="" /p:TargetFrameworkProfile="" ./src/System.Drawing.Analysis.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/System.Drawing.Analysis.Testing/bin/Release/System.Drawing.Analysis.Testing.dll
