language: csharp
solution: ./src/System.Drawing.Analysis.sln
script:
  - xbuild /p:Configuration=Release /p:PostBuildEventUseInBuild=false /p:PreBuildEvent="" /p:PostBuildEvent="" /p:TargetFrameworkProfile="" ./src/System.Drawing.Analysis.sln
