language: csharp
solution: ./src/System.Drawing.Analysis.sln
install:
  - nuget restore ./src/System.Drawing.Analysis.sln
  - nuget install Microsoft.VisualStudio.QualityTools.UnitTestFramework
script:
  - xbuild /p:Configuration=Release /p:PostBuildEventUseInBuild=false /p:PreBuildEvent="" /p:PostBuildEvent="" /p:TargetFrameworkProfile="" ./src/System.Drawing.Analysis.sln
